abbyhudson13/intiMASKy

- app/views/layouts/application.html.erb
added the files for the front end components
> adding navbar file

- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_content_options.html.erb
Quick update to make Ben and Abby's frontend layouts work together
> front end cleanup

- app/views/shared/_content_options.html.erb
I created a new search page and updated the top margin of the nav bar.
> Mask search page

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_content_options.scss
- app/views/masks/index.html.erb
- app/views/masks/new.html.erb
- app/views/shared/_content_options.html.erb
fixing flex of cards on homepage, adding flex to index cards
> fixing flex layouts

- app/assets/stylesheets/components/_banner.scss
- db/schema.rb
> fix banner

- app/controllers/bookings_controller.rb
- app/models/booking.rb
- app/views/bookings/_form.html.erb
- app/views/bookings/new.html.erb
Please, do NOT merge my pull request to master yet!
@mcstr 
The form for a new booking did't work correctly that's why I changed and tested it. Now it seems to work. Let's discuss tomorrow morning why it didn't work, what I changed and why.
> Modifies the form for new booking; adds validation for booking

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_card.scss
- app/views/masks/index.html.erb
- app/views/masks/new.html.erb
created a new container 'container-mask' with vw of 97
amended height of container
> amending container

- app/assets/stylesheets/components/_content_options.scss
- app/views/shared/_content_options.html.erb
I adjusted the landing page container to be 100% of the screen and then i centered the cards on this div.
> Adjusted the css of the landing page container

- app/assets/stylesheets/components/_card.scss
- app/views/masks/index.html.erb
> finalising cards for index page

- app/assets/stylesheets/components/_card.scss
- app/models/mask.rb
- config/environments/production.rb
added auto margin so image always centers
> Amend card margin

- app/assets/stylesheets/components/_content_options.scss
cloudinary images for cards are still not working on heroku- added " to see if this works
> added quotes to css to fix cloudinary issue

- app/assets/stylesheets/components/_index.scss
need to do this in order to switch to master, sorry not much code changed
> adding button class

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/pages/_search.scss
- app/views/layouts/application.html.erb
- app/views/masks/index.html.erb
- app/views/pages/search.html.erb
fixed flex so that container stretches according to contact, made the index and search pages responsive
> fixing flex on mask container, amending cards

- app/assets/stylesheets/components/_button.scss
- app/views/masks/index.html.erb
defining a button for submit actions
> added a new button for submit

- app/controllers/bookings_controller.rb
- app/controllers/pages_controller.rb
- app/views/pages/dashboard.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
adding dashboard with users bookings and the masks they uploaded
> adding dashboard

- app/views/masks/index.html.erb
- app/views/pages/dashboard.html.erb
- app/views/shared/_navbar.html.erb
changing flex so that cards are centered
> Change flex

- app/views/layouts/application.html.erb
> added favicon to tab

- app/views/pages/dashboard.html.erb
Reverts abbyhudson13/intiMASKy#79
> Revert "minor change to dashboard"

- app/javascript/components/navbar.js
amended so class changes after 200px scroll instead of full window
> amending navbar so scroll function works on all pages

- app/controllers/bookings_controller.rb
- app/controllers/masks_controller.rb
- app/javascript/components/navbar.js
- app/views/pages/dashboard.html.erb
- config/routes.rb
user can now edit their posts from the dashboard
> Edit bookings

- app/controllers/bookings_controller.rb
- app/controllers/masks_controller.rb
- app/javascript/components/navbar.js
- app/views/pages/dashboard.html.erb
- config/routes.rb
user can now cancel their bookings from dashboard
> Cancel bookings

- app/controllers/bookings_controller.rb
- app/controllers/masks_controller.rb
- app/javascript/components/navbar.js
- app/views/masks/show.html.erb
- app/views/pages/dashboard.html.erb
- app/views/pages/search.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
making featured masks a random array of 4 masks
> Featured masks

- app/views/masks/_form.html.erb
> change submit button on form

- app/views/masks/_form.html.erb
- app/views/pages/search.html.erb
amend class on button so its styled properly
> Search button

- app/views/bookings/new.html.erb
amending style of booking button
> Booking button

- app/models/mask.rb
> adding new categories

- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_show.scss
fixed image sizing on show page
> Image sizing

- app/assets/stylesheets/pages/_show.scss
> fixing image distortion on show page
